#pragma config(Motor,  port2,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftSpin,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           rightSpin,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           shooter,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           sucker,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	How to drive:
		right side forward/back -> right joystick forward + back
		left side forward/back  -> left joystick forward + back

	How to shoot:
		shoot (top)             -> upper right trigger (6U)

	How to pick up/spit out balls:
		pick up (top)           -> upper left trigger (5U)
		spit out (bottom)       -> lower left trigger (5D)
	*/

	while(true) {

		//drive
		motor[left] = vexRT[Ch3];
		motor[right] = vexRT[Ch2];

		if (vexRT[Btn6U]) { 				//shoot
			motor[shooter] = 150;
			motor[leftSpin] = 50;
			motor[rightSpin] = 50;
			motor[sucker] = 0;
		}else if (vexRT[Btn5U]){  //pick up
			motor[sucker] = 50;
			motor[leftSpin] = 50;
			motor[rightSpin] = 50;
			motor[shooter] = 0;
		}else if (vexRT[Btn5D]) {  //spit out
			motor[sucker] = -50;
			motor[leftSpin] = -50;
			motor[rightSpin] = -50;
			motor[shooter] = 0;
		} else { 									 //nothing -> turn off everything
			motor[sucker] = 0;
			motor[leftSpin] = 0;
			motor[rightSpin] = 0;
			motor[shooter] = 0;
		}
	}
}
